version: "2.1"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: /home/app/application-code/scripts/start.sh
    ports:
      - "4000:4000"
    volumes:
      - .:/home/app/application-code
